#!/bin/bash 
awk -F: '( $3 == "0") {print}' /etc/passwd && 
awk -F: '( $2 == "" ) {print}' /etc/shadow && 

echo 'bad permissions, writeable to world'
find / -xdev -type d \( -perm -0002 -a ! -perm -1000 \) -print && 
echo  'no users and no groups'
find / -xdev \( -nouser -o -nogroup \) -print &&
netstat -tulpn 
